on:
  push:
    branches:
      - 'release'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
  
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Show DNS Configuration
        run: cat /etc/resolv.conf
  
      - name: Test DNS Resolution for Known Domain
        run: |
          nslookup google.com
          dig google.com
  
      - name: Test DNS with Google DNS
        run: |
          nslookup ${{ secrets.DEPLOY_WEBHOOK_URL  }} 8.8.8.8
          dig @8.8.8.8 ${{ secrets.DEPLOY_WEBHOOK_URL  }}
  
      - name: Test DNS with Cloudflare DNS
        run: |
          nslookup ${{ secrets.DEPLOY_WEBHOOK_URL  }} 1.1.1.1
          dig @1.1.1.1 ${{ secrets.DEPLOY_WEBHOOK_URL  }}
        
      - name: Test curl command
        run: |
          curl -v ${{ secrets.DEPLOY_WEBHOOK_URL  }}
