on:
  push:
    branches:
      - 'release'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
  
  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DNS Resolution Test
        run: |
          nslookup ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          dig ${{ secrets.DEPLOY_WEBHOOK_URL  }}
  
      - name: Traceroute to Hostname
        run: traceroute ${{ secrets.DEPLOY_WEBHOOK_URL  }}
  
      - name: Test Curl to Hostname
        run: curl -v ${{ secrets.DEPLOY_WEBHOOK_URL  }}
  
      - name: Test Curl to Google
        run: curl -v https://www.google.com
  
      - name: Show Network Interfaces
        run: ip addr show
  
      - name: Show Routing Table
        run: ip route show
  
      - name: Show DNS Configuration
        run: cat /etc/resolv.conf
        
      - name: Test curl command
        run: |
          curl -v ${{ secrets.DEPLOY_WEBHOOK_URL  }}
